class Localization {
  static String activeLanguage = 'en';

  static const Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': "Tuition Manager",
      'studentMgmt': "Student Management",
      'financeSummary': "Financial Summary",
      'newRequests': "New Requests",
      'monthlyFees': "Monthly Fees",
      'files': "Files",
      'teacherLogin': "Teacher Login",
      'studentLogin': "Student Login",
      'createAccount': "Create Account",
      'email': "Email",
      'mobileNo': "Mobile No.",
      'password': "Password",
      'forgotPassword': "Forgot Password?",
      'login': "Login",
      'newStudent': "New Student?",
      'fullName': "Full Name",
      'class': "Class",
      'fixedFee': "Monthly Fee",
      'joinDate': "Joining Date",
      'attendance': "Attendance",
      'routine': "Routine",
      'sendPdf': "Send PDF",
      'studentFiles': "Student Files",
      'resetPass': "Reset Pass",
      'delete': "Delete",
      'academicYear': "Academic Year (12 Months)",
      'paidAmount': "Paid Amount",
      'paidDate': "Paid Date",
      'dueAmount': "Due Amount",
      'extraPay': "Extra Pay / Advance",
      'studentSign': "Student Sign",
      'teacherSign': "Teacher Sign",
      'saveMonthlyData': "Save Monthly Data",
      'monthlyReport': "Monthly Report",
      'yearlyReport': "Yearly (2026)",
      'totalCollected': "Total Collected",
      'totalDue': "Total Due",
      'classes': "Classes",
      'present': "Present",
      'absent': "Absent",
      'done': "Done",
      'cancel': "Cancel",
    },
    'bn': {
      'appTitle': "টিউশন ম্যানেজার",
      'studentMgmt': "ছাত্র পরিচালনা",
      'financeSummary': "আর্থিক সারসংক্ষেপ",
      'newRequests': "নতুন অনুরোধ",
      'monthlyFees': "মাসিক ফি",
      'files': "ফাইল সমূহ",
      'teacherLogin': "শিক্ষক লগইন",
      'studentLogin': "ছাত্র লগইন",
      'createAccount': "অ্যাকাউন্ট তৈরি করুন",
      'email': "ইমেল",
      'mobileNo': "মোবাইল নম্বর",
      'password': "পাসওয়ার্ড",
      'forgotPassword': "পাসওয়ার্ড ভুলে গেছেন?",
      'login': "লগইন",
      'newStudent': "নতুন ছাত্র?",
      'fullName': "সম্পূর্ণ নাম",
      'class': "শ্রেণী",
      'fixedFee': "মাসিক ফি",
      'joinDate': "যোগদানের তারিখ",
      'attendance': "উপস্থিতি",
      'routine': "রুটিন",
      'sendPdf': "পিডিএফ পাঠান",
      'studentFiles': "ছাত্রের ফাইল",
      'resetPass': "পাসওয়ার্ড রিসেট",
      'delete': "মুছুন",
      'academicYear': "শিক্ষাবর্ষ (১২ মাস)",
      'paidAmount': "পরিশোধিত টাকা",
      'paidDate': "পরিশোধের তারিখ",
      'dueAmount': "বকেয়া টাকা",
      'extraPay': "অতিরিক্ত পরিশোধ",
      'studentSign': "ছাত্রের স্বাক্ষর",
      'teacherSign': "শিক্ষকের স্বাক্ষর",
      'saveMonthlyData': "মাসিক তথ্য সংরক্ষণ করুন",
      'monthlyReport': "মাসিক রিপোর্ট",
      'yearlyReport': "বার্ষিক (২০২৬)",
      'totalCollected': "মোট সংগ্রহ",
      'totalDue': "মোট বকেয়া",
      'classes': "শ্রেণী সমূহ",
      'present': "উপস্থিত",
      'absent': "অনুপস্থিত",
      'done': "সম্পন্ন",
      'cancel': "বাতিল",
    },
    'hi': {
      'appTitle': "ट्यूशन प्रबंधक",
      'studentMgmt': "छात्र प्रबंधन",
      'financeSummary': "वित्तीय सारांश",
      'newRequests': "नए अनुरोध",
      'monthlyFees': "मासिक शुल्क",
      'files': "फ़ाइलें",
      'teacherLogin': "शिक्षक लॉगिन",
      'studentLogin': "छात्र लॉगिन",
      'createAccount': "खाता बनाएं",
      'email': "ईमेल",
      'mobileNo': "मोबाइल नंबर",
      'password': "पासवर्ड",
      'forgotPassword': "पासवर्ड भूल गए?",
      'login': "लॉगिन",
      'newStudent': "नए छात्र?",
      'fullName': "पूरा नाम",
      'class': "कक्षा",
      'fixedFee': "मासिक शुल्क",
      'joinDate': "शामिल होने की तिथि",
      'attendance': "उपस्थिति",
      'routine': "दिनचर्या",
      'sendPdf': "पीडीएफ भेजें",
      'studentFiles': "छात्र फाइलें",
      'resetPass': "पासवर्ड रीसेट",
      'delete': "हटाएं",
      'academicYear': "शैक्षणिक वर्ष (12 महीने)",
      'paidAmount': "भुगतान राशि",
      'paidDate': "भुगतान तिथि",
      'dueAmount': "बकाया राशि",
      'extraPay': "अतिरिक्त भुगतान",
      'studentSign': "छात्र हस्ताक्षर",
      'teacherSign': "शिक्षक हस्ताक्षर",
      'saveMonthlyData': "मासिक डेटा सहेजें",
      'monthlyReport': "मासिक रिपोर्ट",
      'yearlyReport': "वार्षिक (2026)",
      'totalCollected': "कुल एकत्र",
      'totalDue': "कुल बकाया",
      'classes': "कक्षाएं",
      'present': "उपस्थित",
      'absent': "अनुपस्थित",
      'done': "हो गया",
      'cancel': "रद्द करें",
    },
    'as': {
      'appTitle': "টিউচন মেনেজাৰ",
      'studentMgmt': "ছাত্ৰ পৰিচালনা",
      'financeSummary': "বিত্তীয় সাৰাংশ",
      'newRequests': "নতুন অনুৰোধ",
      'monthlyFees': "মাহিলী মাচুল",
      'files': "ফাইলসমূহ",
      'teacherLogin': "শিক্ষক লগইন",
      'studentLogin': "ছাত্ৰ লগইন",
      'createAccount': "অ্যাকাউন্ট সৃষ্টি কৰক",
      'email': "ইমেইল",
      'mobileNo': "মোবাইল নম্বৰ",
      'password': "পাছৱৰ্ড",
      'forgotPassword': "পাছৱৰ্ড পাহৰিলে?",
      'login': "লগইন",
      'newStudent': "নতুন ছাত্ৰ?",
      'fullName': "সম্পূৰ্ণ নাম",
      'class': "শ্ৰেণী",
      'fixedFee': "মাহিলী মাচুল",
      'joinDate': "যোগদানৰ তাৰিখ",
      'attendance': "উপস্থিতি",
      'routine': "ৰুটিন",
      'sendPdf': "পিডিএফ পঠাওক",
      'studentFiles': "ছাত্ৰৰ ফাইল",
      'resetPass': "পাছৱৰ্ড ৰিচেট",
      'delete': "মচি দিয়ক",
      'academicYear': "শৈক্ষিক বৰ্ষ (১২ মাহ)",
      'paidAmount': "পৰিশোধিত ধন",
      'paidDate': "পৰিশোধৰ তাৰিখ",
      'dueAmount': "বকেয়া ধন",
      'extraPay': "অতিৰিক্ত পৰিশোধ",
      'studentSign': "ছাত্ৰৰ স্বাক্ষৰ",
      'teacherSign': "শিক্ষকৰ স্বাক্ষৰ",
      'saveMonthlyData': "মাহিলী তথ্য সংৰক্ষণ কৰক",
      'monthlyReport': "মাহিলী ৰিপোৰ্ট",
      'yearlyReport': "বাৰ্ষিক (২০২৬)",
      'totalCollected': "মুঠ সংগৃহীত",
      'totalDue': "মুঠ বকেয়া",
      'classes': "শ্ৰেণীসমূহ",
      'present': "উপস্থিত",
      'absent': "অনুপস্থিত",
      'done': "সম্পন্ন",
      'cancel': "বাতিল",
    },
    'ko': {
      'appTitle': "수업 관리자",
      'studentMgmt': "학생 관리",
      'financeSummary': "재무 요약",
      'newRequests': "새 요청",
      'monthlyFees': "월 사용료",
      'files': "파일들",
      'teacherLogin': "교사 로그인",
      'studentLogin': "학생 로그인",
      'createAccount': "계정 생성",
      'email': "이메일",
      'mobileNo': "휴대폰 번호",
      'password': "비밀번호",
      'forgotPassword': "비밀번호를 잊으셨나요?",
      'login': "로그인",
      'newStudent': "신규 학생?",
      'fullName': "이름",
      'class': "학급",
      'fixedFee': "월 수강료",
      'joinDate': "가입일",
      'attendance': "출석",
      'routine': "스케줄",
      'sendPdf': "PDF 전송",
      'studentFiles': "학생 파일",
      'resetPass': "비밀번호 초기화",
      'delete': "삭제",
      'academicYear': "학년도 (12개월)",
      'paidAmount': "납부액",
      'paidDate': "납부일",
      'dueAmount': "미납액",
      'extraPay': "추가 납부",
      'studentSign': "학생 서명",
      'teacherSign': "교사 서명",
      'saveMonthlyData': "월간 데이터 저장",
      'monthlyReport': "월간 보고서",
      'yearlyReport': "연간 보고서 (2026)",
      'totalCollected': "총 수금액",
      'totalDue': "총 미납액",
      'classes': "클래스 목록",
      'present': "출석",
      'absent': "결석",
      'done': "완료",
      'cancel': "취소",
    }
  };

  static String get(String key) {
    return translations[activeLanguage]?[key] ?? key;
  }
}
